#!/bin/bash

export NVM_DIR=~/.nvm

source "$NVM_DIR/nvm.sh"
nvm use default

source scripts/setup_env

if [ "${ALTEXO_PRETTY_STDOUT}" = true ] ; then
	exec node index.js --config="${ALTEXO_CHAT_CONFIG}" | ./node_modules/.bin/bunyan --output short
else
	exec node index.js --config="${ALTEXO_CHAT_CONFIG}"
fi
